import ShapesPackage.ShapeErrorModule
import ShapesPackage.ShapeModule
import ShapesPackage.OpenShapeErrorModule
import ShapesPackage.OpenShapeModule
import ShapesPackage.ClosedShapeErrorModule
import ShapesPackage.ClosedShapeModule
import ShapesPackage.PointErrorModule
import ShapesPackage.PointModule

#import LinesPackage.LineModule
#import PlanesPackage.PlaneModule
#import PolygonsPackage.PolygonModule
#import PolyhedronsPackage.PolyhedronModule
#import EllipsesPackage.EllipseModule
#import EllipsoidsPackage.EllipsoidModule

#import TrianglesPackage.TriangleModule  -- closed polygon