import AlgebraPackage.AlgebraErrorModule
import AlgebraPackage.AlgebraModule
#import CoordinatesPackage.CoordinatesModule
#import LinesPackage.LineModule
#import LogicPackage.LogicModule
#import NumberSystemsPackage.NumberSystemModule