import Classes.Math.errors.ArithmaticError as ArithmaticError
import Classes.Math.Arithmatic as Arithmatic
import Classes.Math.Algebra.errors.AlgebraError as AlgebraError
import Classes.Math.Algebra.Algebra as Algebra
import Classes.Math.Geometry.errors.GeometryError as GeometryError
import Classes.Math.Geometry.Geometry as Geometry
import Classes.Math.Trigonometry.errors.TrigonometryError as TrigonometryError
import Classes.Math.Trigonometry.Trigonometry as Trigonometry
import Classes.Math.Calculus.errors.CalculusError as CalculusError
import Classes.Math.Calculus.Calculus as Calculus