import CodeTestingPackage.TestModule
import CodeTestingPackage.TestErrorModule
import CodeTestingPackage.TestCaseModule
import CodeTestingPackage.TestCaseErrorModule

CodeTestingPackage.test_testCases.py