import CodeTestingPackage.TestModule
import CodeTestingPackage.TestErrorModule
import CodeTestingPackage.TestCaseModule
import CodeTestingPackage.TestCaseErrorModule

import CodeTestingPackage.test_testCases as test
test