import Classes.Math.Trigonometry.Triangles.errors.PythagorianError as PythagorianError
import Classes.Math.Trigonometry.Triangles.errors.AcuteTriangleError as AcuteTriangleError
import Classes.Math.Trigonometry.Triangles.Acute as Acute
import Classes.Math.Trigonometry.Triangles.errors.ObtuseTriangleError as ObtuseTriangleError
import Classes.Math.Trigonometry.Triangles.Obtuse as Obtuse
import Classes.Math.Trigonometry.Triangles.errors.RightTriangleError as RightTriangleError
import Classes.Math.Trigonometry.Triangles.Right as Right
import Classes.Math.Trigonometry.Triangles.errors.ScaleneTriangleError as ScaleneTriangleError
import Classes.Math.Trigonometry.Triangles.Scalene as Scalene
import Classes.Math.Trigonometry.Triangles.errors.IsoscelesTriangleError as IsoscelesTriangleError
import Classes.Math.Trigonometry.Triangles.Isosceles as Isosceles
import Classes.Math.Trigonometry.Triangles.errors.EqualateralTriangleError as EqualateralTriangleError
import Classes.Math.Trigonometry.Triangles.Equalateral as Equalateral