import Classes.Math.Algebra.NumberSystems.errors.BinaryNumberSystemError as BinaryNumberSystemError
import Classes.Math.Algebra.NumberSystems.BinaryNumberSystem as BinaryNumberSystem
import Classes.Math.Algebra.NumberSystems.errors.TrinaryNumberSystemError as TrinaryNumberSystemError
import Classes.Math.Algebra.NumberSystems.TrinaryNumberSystem as TrinaryNumberSystem
import Classes.Math.Algebra.NumberSystems.errors.OctalError as OctalError
import Classes.Math.Algebra.NumberSystems.Octal as Octal
import Classes.Math.Algebra.NumberSystems.errors.DecimalError as DecimalError
import Classes.Math.Algebra.NumberSystems.Decimal as Decimal
import Classes.Math.Algebra.NumberSystems.errors.HexadecimalError as HexadecimalError
import Classes.Math.Algebra.NumberSystems.Hexadecimal as Hexadecimal