import Classes.Math.Geometry.Shapes.Triangles.errors.PythagorianError as PythagorianError
import Classes.Math.Geometry.Shapes.Triangles.errors.AcuteTriangleError as AcuteTriangleError
import Classes.Math.Geometry.Shapes.Triangles.functions.AreaOfRightTriangle as AreaOfRightTriangle
import Classes.Math.Geometry.Shapes.Triangles.functions.DoAnglesFormTriangle as DoAnglesFormTriangle
import Classes.Math.Geometry.Shapes.Triangles.functions.AssertAnglesFormTriangle as AssertAnglesFormTriangle
import Classes.Math.Geometry.Shapes.Triangles.functions.AreaOfTriangle as AreaOfTriangle
import Classes.Math.Geometry.Shapes.Triangles.functions.BaseOfTriangle as BaseOfTriangle
import Classes.Math.Geometry.Shapes.Triangles.functions.HeightOfTriangle as HeightOfTriangle
import Classes.Math.Geometry.Shapes.Triangles.functions.SemiPerimeterOfTriangle as SemiPerimeterOfTriangle
import Classes.Math.Geometry.Shapes.Triangles.functions.PerimeterOfTriangle as PerimeterOfTriangle
import Classes.Math.Geometry.Shapes.Triangles.functions.LengthOfMedian as LengthOfMedian
import Classes.Math.Geometry.Shapes.Triangles.functions.InradiusOfTriangle as InradiusOfTriangle
import Classes.Math.Geometry.Shapes.Triangles.functions.CircumradiusOfTriangle as CircumradiusOfTriangle
import Classes.Math.Geometry.Shapes.Triangles.functions.HeronsAreaOfTriangle as HeronsAreaOfTriangle
import Classes.Math.Geometry.Shapes.Triangles.functions.AngleFromSides as AngleFromSides
import Classes.Math.Geometry.Shapes.Triangles.functions.AssertTriangleSidesSumRule as AssertTriangleSidesSumRule
import Classes.Math.Geometry.Shapes.Triangles.functions.TriangleSidesSumRule as TriangleSidesSumRule
import Classes.Math.Geometry.Shapes.Triangles.functions.AssertTriangle as AssertTriangle
import Classes.Math.Geometry.Shapes.Triangles.functions.SolveTriangle as SolveTriangle
import Classes.Math.Geometry.Shapes.Triangles.functions.OppositeSideFromAngleAngleExteriorSide as OppositeSideFromAngleAngleExteriorSide
import Classes.Math.Geometry.Shapes.Triangles.functions.OppositeAngleFromSideSideExteriorAngle as OppositeAngleFromSideSideExteriorAngle
import Classes.Math.Geometry.Shapes.Triangles.functions.OppositeSideFromSideSideInteriorAngle as OppositeSideFromSideSideInteriorAngle

import Classes.Math.Geometry.Shapes.Triangles.Acute as AcuteTriangle
import Classes.Math.Geometry.Shapes.Triangles.errors.ObtuseTriangleError as ObtuseTriangleError
import Classes.Math.Geometry.Shapes.Triangles.Obtuse as ObtuseTriangle
import Classes.Math.Geometry.Shapes.Triangles.errors.RightTriangleError as RightTriangleError
import Classes.Math.Geometry.Shapes.Triangles.Right as RightTriangle
import Classes.Math.Geometry.Shapes.Triangles.errors.ScaleneTriangleError as ScaleneTriangleError
import Classes.Math.Geometry.Shapes.Triangles.Scalene as ScaleneTriangle
import Classes.Math.Geometry.Shapes.Triangles.errors.IsoscelesTriangleError as IsoscelesTriangleError
import Classes.Math.Geometry.Shapes.Triangles.Isosceles as IsoscelesTriangle
import Classes.Math.Geometry.Shapes.Triangles.errors.EqualateralTriangleError as EqualateralTriangleError
import Classes.Math.Geometry.Shapes.Triangles.Equalateral as EqualateralTriangle