import Classes.Math.Geometry.Shapes.Triangles.errors.PythagorianError as PythagorianError
import Classes.Math.Geometry.Shapes.Triangles.errors.AcuteTriangleError as AcuteTriangleError
import Classes.Math.Geometry.Shapes.Triangles.Acute as AcuteTriangle
import Classes.Math.Geometry.Shapes.Triangles.errors.ObtuseTriangleError as ObtuseTriangleError
import Classes.Math.Geometry.Shapes.Triangles.Obtuse as ObtuseTriangle
import Classes.Math.Geometry.Shapes.Triangles.errors.RightTriangleError as RightTriangleError
import Classes.Math.Geometry.Shapes.Triangles.Right as RightTriangle
import Classes.Math.Geometry.Shapes.Triangles.errors.ScaleneTriangleError as ScaleneTriangleError
import Classes.Math.Geometry.Shapes.Triangles.Scalene as ScaleneTriangle
import Classes.Math.Geometry.Shapes.Triangles.errors.IsoscelesTriangleError as IsoscelesTriangleError
import Classes.Math.Geometry.Shapes.Triangles.Isosceles as IsoscelesTriangle
import Classes.Math.Geometry.Shapes.Triangles.errors.EqualateralTriangleError as EqualateralTriangleError
import Classes.Math.Geometry.Shapes.Triangles.Equalateral as EqualateralTriangle