import Classes.Math.Geometry.Shapes.Triangles.errors.AcuteError as AcuteError
import Classes.Math.Geometry.Shapes.Triangles.Acute as Acute
import Classes.Math.Geometry.Shapes.Triangles.errors.ObtuseError as ObtuseError
import Classes.Math.Geometry.Shapes.Triangles.Obtuse as Obtuse
import Classes.Math.Geometry.Shapes.Triangles.errors.RightError as RightError
import Classes.Math.Geometry.Shapes.Triangles.Right as Right
import Classes.Math.Geometry.Shapes.Triangles.errors.ScaleneError as ScaleneError
import Classes.Math.Geometry.Shapes.Triangles.Scalene as Scalene
import Classes.Math.Geometry.Shapes.Triangles.errors.IsoscelesError as IsoscelesError
import Classes.Math.Geometry.Shapes.Triangles.Isosceles as Isosceles
import Classes.Math.Geometry.Shapes.Triangles.errors.EqualateralError as EqualateralError
import Classes.Math.Geometry.Shapes.Triangles.Equalateral as Equalateral